[package]
name = "purs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
dirs = "4.0.0"
serde_json = "1.0.79"
futures-util = "0.3.21"
log = "0.4.14"

[dependencies.reqwest]
version = "0.11.9"
default-features = false
features = ["rustls-tls", "stream"]